# Generated by Django 3.2.8 on 2021-10-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsUp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_name',
            old_name='User_ID',
            new_name='Username',
        ),
    ]
